### ISSUE TITLE
Only applying plugin to certain routes

### ISSUE THREAD

**Issue by ethanve** [developmentseed/hapi-paginate#4]
Thanks for creating this. I'm new to Hapi in general and I would like to apply this plugin only to certain routes. How Would I go about doing so?

Thanks

**Comment by scisco** [comment]
@ethanve That's a nice feature we should add. Unfortunately, the current version adds the pagination to all routes.

I'll update the plugin to add this feature very soon and will keep you posted.

**Comment by scisco** [comment]
@ethanve I released a new version that includes the routes option.

You just have to add routes to the options of the plugins. `routes` accepts an array of routes. Here is an example:

```
hapi.register({
  register: require('hapi-paginate'),
  options: {
    limit: 1000,
    name: 'My Meta',
    results: 'output',
    routes: ['/', '/api']
  }
};
```
